version: '3.9'

services:
  postgres:
    container_name: 'postgres'
    ports:
     - "5432:5432"
    environment:
        POSTGRES_DB: "Products"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "password"
    image: 
        postgres:15.6-alpine3.19